backend/controllers/PortfolioController.php
<?php

namespace backend\controllers;

use common\models\portfolio\PortfolioStockCollection;
use common\models\PortfolioStock;
use JetBrains\PhpStorm\ArrayShape;
use Yii;
use common\models\Portfolio;
use common\models\PortfolioSearch;
use yii\base\InvalidConfigException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * PortfolioController implements the CRUD actions for Portfolio model.
 */
class PortfolioController extends BaseController
{
    public ?Portfolio $portfolio = null;

    /**
     * @inheritdoc
     */
    public function behaviors(): array
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Portfolio models.
     * @return mixed
     */
    public function actionIndex(): string
    {
        $searchModel = new PortfolioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param integer $id
     *
     * @return mixed
     *
     * @throws NotFoundHttpException
     */
    public function actionView(int $id): string
    {
        $model = $this->findModel($id);

        $model->stock_type = Yii::$app->request->get('type');
        $stockGroup = PortfolioStockCollection::getStockGroup($model);

        if (Yii::$app->request->isAjax) {
            return $this->renderPartial('_view-pjax', [
                'model' => $model,
                'stockGroup' => $stockGroup,
            ]);
        }

        return $this->render('view', [
            'model' => $model,
            'stockGroup' => $stockGroup,
        ]);
    }

    /**
     * @param integer $id
     *
     * @return mixed
     *
     * @throws NotFoundHttpException
     */
    public function actionViewClose(int $id): string
    {
        $model = $this->findModel($id);

        $stockGroupClose = PortfolioStockCollection::getStockGroupClose($model);
        usort($stockGroupClose, fn($a, $b) => strcmp($a->name, $b->name));

        return $this->render('view-close', [
            'model' => $model,
            'stockGroupClose' => $stockGroupClose,
        ]);
    }

    /**
     * @param integer $id
     *
     * @return mixed
     *
     * @throws NotFoundHttpException
     * @throws InvalidConfigException
     */
    #[ArrayShape(['meta' => "array", 'items' => "array"])]
    public function actionViewUpdate(int $id): array
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $model = $this->findModel($id);

        $formatter = Yii::$app->formatter;
        $model->stock_type = Yii::$app->request->get('type');
        $stockGroup = PortfolioStockCollection::getStockGroup($model);

        $result = [
            'meta' => [
                'portfolioProfit' => $formatter->asCurrency($model->profitType()),
                'portfolioCurrentPrice' => $formatter->asCurrency($model->totalPriceCurrentType()),
                'changePercent' => $model->changePercentType() . '%',
                'changeDay' => $formatter->asCurrency($model->getChangeDay()),
                'changePercentDay' => $model->getChangePercentDay() . '%',
            ],
            'items' => [],
        ];

        foreach ($stockGroup as $collection) {
            $result['items'][$collection->getTicker()] = [
                'percentDay' => $collection->getPercentDay() . '%',
                'currentPercent' => $collection->getPercentCurrent() . '%',
                'currentPrice' => $formatter->stockCurrency($collection->getPriceCurrent(), $collection->getCurrency()),
                'totalPriceCurrent' => $formatter->asCurrency($collection->totalPriceCurrent(), $collection->getCurrency()),
                'profit' => $formatter->asCurrency($collection->profit(), $collection->getCurrency()),
                'percentToPurpose' => $collection->percentToPurpose() . '%',
                'percentToStopLoss' => $collection->percentToStopLoss() . '%',
            ];
        }

        return $result;
    }

    /**
     * @param $stock_id
     *
     * @return string
     */
    public function actionStockView($stock_id): string
    {
        $model = PortfolioStock::findOne($stock_id);

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('stock/_view', [
                'model' => $model,
            ]);
        }

        return $this->render('stock/_view', [
            'model' => $model,
        ]);
    }

    /**
     * @return string|Response
     */
    public function actionCreate(): Response|string
    {
        $model = new Portfolio();

        $model->user_id = Yii::$app->getUser()->getId();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $searchModel = new PortfolioSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->asJson([
                'reloadBlock' => [[
                    'selector' => '.portfolio-grid',
                    'content' => $this->renderAjax('_index', [
                        'dataProvider' => $dataProvider,
                    ]),
                ]],
            ]);
        }

        return $this->renderPartial('create', [
            'model' => $model,
        ]);
    }

    /**
     * @param integer $id
     *
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate(int $id): mixed
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $searchModel = new PortfolioSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->asJson([
                'reloadBlock' => [[
                    'selector' => '.portfolio-grid',
                    'content' => $this->renderAjax('_index', [
                        'dataProvider' => $dataProvider,
                    ]),
                ]],
            ]);
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderPartial('update', [
                'model' => $model,
            ]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     *
     * @return string|Response
     *
     * @throws NotFoundHttpException
     */
    public function actionStockCreate($id): Response|string
    {
        $portfolio = $this->findModel($id);

        $model = new PortfolioStock();
        $model->portfolio_id = $portfolio->id;
        $model->date = date('Y-m-d');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['portfolio/view', 'id' => $portfolio->id]);
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('stock/create', [
                'model' => $model,
            ]);
        }

        return $this->render('stock/create', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @param $stock_id
     *
     * @return string|Response
     */
    public function actionStockClose($id, $stock_id): Response|string
    {
        $model = new PortfolioStock();
        $model->portfolio_id = $id;
        $model->stock_id = $stock_id;
        $model->date_close = date('Y-m-d');

        if (Yii::$app->request->isPost) {
            if ($model->load(Yii::$app->request->post()) && $model->closePosition()) {
                return $this->redirect(['portfolio/view', 'id' => $id]);
            }
        }

        return $this->renderWithAjax('stock/close', [
            'model' => $model,
        ]);
    }

    /**
     * @param integer $stock_id
     *
     * @return string|Response
     *
     * @throws NotFoundHttpException
     */
    public function actionStockUpdate(int $stock_id): string|Response
    {
        $model = $this->findModelStock($stock_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['portfolio/view', 'id' => $model->portfolio_id]);
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('stock/update', [
                'model' => $model,
            ]);
        }

        return $this->render('stock/update', [
            'model' => $model,
        ]);
    }

    /**
     * @param integer $id
     * @return mixed
     *
     * @throws NotFoundHttpException
     * @throws yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * @param integer $id
     *
     * @return Portfolio
     * @throws NotFoundHttpException
     */
    protected function findModel(int $id): Portfolio
    {
        if ($this->portfolio && $this->portfolio->id === $id) {
            return $this->portfolio;
        }

        if (($model = Portfolio::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * @param integer $id
     *
     * @return PortfolioStock
     * @throws NotFoundHttpException
     */
    protected function findModelStock($id): PortfolioStock
    {
        if (($model = PortfolioStock::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/portfolio/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Portfolio */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="portfolio-form">
    <?php $form = ActiveForm::begin(['id' => $model->formId()]); ?>

    <div class="box-body table-responsive">
        <?= $form->field($model, 'user_id')->textInput() ?>

        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

backend/views/portfolio/_index.php
<?php

use common\models\Portfolio;
use common\widgets\Modal\ModalWidget;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel common\models\PortfolioSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>

<?php // echo $this->render('_search', ['model' => $searchModel]); ?>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
//    'filterModel' => $searchModel,
    'layout' => "{items}\n{summary}\n{pager}",
    'columns' => [
        'name',
        'count_stock' => [
            'class' => 'yii\grid\DataColumn',
            'contentOptions' => ['class' => 'text-right'],
            'label' => 'Кол. акций',
            'attribute' => 'count_stock',
            'content' => function(Portfolio $model) {
                return count($model->portfolioStocks);
            },
        ],
        'total_price' => [
            'class' => 'yii\grid\DataColumn',
            'contentOptions' => ['class' => 'text-right'],
            'label' => 'Нач. стоим.',
            'attribute' => 'total_price',
            'format' => 'decimal',
            'content' => function(Portfolio $model) {
                return Yii::$app->formatter->asDecimal($model->totalPrice(), 2);
            },
            'footer' => 123,
        ],
        'total_price_current' => [
            'contentOptions' => ['class' => 'text-right'],
            'label' => 'Teк. стоим.',
            'attribute' => 'total_price_current',
            'content' => function(Portfolio $model) {
                return Yii::$app->formatter->asDecimal($model->totalPriceCurrent(), 2);
            },
        ],
        'profit' => [
            'contentOptions' => ['class' => 'text-right'],
            'label' => 'Прибыль',
            'attribute' => 'profit',
            'content' => function(Portfolio $model) {
                return Yii::$app->formatter->asDecimal($model->profit(), 2);
            },
        ],
        'change' => [
            'contentOptions' => ['class' => 'text-right'],
            'label' => 'Изм %',
            'attribute' => 'change',
            'content' => function(Portfolio $model) {
                return $model->changePercent();
            },
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'buttons' => [
                'view' => function ($url) {
                    return Html::a('<i class="glyphicon glyphicon-eye-open"></i>', $url);
                },
                'update' => function ($url) {
                    return ModalWidget::widget([
                        'url' => $url,
                        'content' => '<i class="glyphicon glyphicon-pencil"></i>',
                    ]);
                },
            ],
        ],
    ],
]); ?>

backend/views/portfolio/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\PortfolioSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="portfolio-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'signs') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/portfolio/_view-collection.php
<?php

use common\helpers\StockHelper;
use common\widgets\Modal\ModalWidget;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Portfolio */
/* @var $stockGroup common\models\portfolio\PortfolioStockCollection[] */

$formatter = Yii::$app->formatter;
?>

<?php foreach ($stockGroup as $collection) : ?>
    <div class="box box-default box-collection collapsed-box ticker-<?= $collection->getTicker() ?>">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-sm-2 col-xs-6 name">
                    <h3 class="box-title stockName" data-widget="collapse">
                        <?= $collection->getName() ?>
                    </h3>
                    <div class="description">
                        <?= $collection->getTicker() ?>
                        &middot;
                        <?= $collection->totalQuantity() ?>
                        &middot;
                        <?= $collection->getPrice() ?>
                        &middot;
                        <span class="stockProportion">
                            <?= $model->getStockProportion($collection->totalPriceCurrent(StockHelper::CURRENCY_SYSTEM)) ?>
                        </span>
                        &hellip;
                    </div>
                </div>

                <div class="col-sm-2 col-xs-3">
                    <div class="description-block  border-right">
                        <span class="description-percentage text-<?= $collection->typeClassDay() ?>">
                            <i class="fa fa-caret-<?= $collection->typeDeviationDay() ?>"></i>
                            <span class="percentDay">
                                <?= $collection->getPercentDay() ?>%
                            </span>
                        </span>
                        (<span class="description-percentage text-<?= $collection->typeClass() ?>"
                               title="<?= StockHelper::getPercentOrEmpty($collection->getPercentCurrencyCurrent()) ?>">
                            <i class="fa fa-caret-<?= $collection->typeDeviation() ?>"></i>
                            <span class="currentPercent">
                                <?= $collection->getPercentCurrent() ?>%
                            </span>
                        </span>)
                        <h5 class="bg-i description-header currentPrice">
                            <?= $formatter->stockCurrency($collection->getPriceCurrent(), $collection->getCurrency()) ?>
                        </h5>
                    </div>
                </div>

                <div class="col-sm-2 col-768-0 col-xs-0">
                    <div class="description-block border-right">
                        <span class="description-percentage text-<?= $collection->typeClassDividend() ?>">
                            <i class="fa fa-caret-<?= $collection->typeDeviationDividend() ?>"></i>
                            <?= $collection->getDividendPercent() ?>%
                        </span>
                        <h5 class="description-header">
                            <?= $formatter->asCurrency($collection->dividend()) ?>
                        </h5>
                    </div>
                </div>

                <div class="col-sm-2 col-768-0 col-xs-0">
                    <div class="description-block border-right">
                        <span class="description-percentage text-<?= $collection->typeClass() ?>">
                            <i class="fa fa-caret-<?= $collection->typeDeviation() ?>"></i>
                            <span>
                                <?= $formatter->asCurrency($collection->profit(), $collection->getCurrency()) ?>
                            </span>
                        </span>
                        <h5 class="bg-i description-header totalPriceCurrent">
                            <?= $formatter->asCurrency($collection->totalPriceCurrent(), $collection->getCurrency()) ?>
                        </h5>
                    </div>
                </div>

                <div class="col-sm-2 col-768-0 col-xs-0">
                    <div class="description-block border-right purpose-block">
                        <span class="description-percentage text-<?= $collection->typeClassPurpose() ?>">
                            <?= $collection->purpose() ?>
                            [<?= $collection->purposePercent() ?>%]
                            [<span class="percentToPurpose"><?= $collection->percentToPurpose() ?>%</span>]
                        </span>
                        <div class="description-percentage text-<?= $collection->typeClassStopLoss() ?>">
                            <?= $collection->stopLoss() ?>
                            [<?= $collection->stopLossPercent() ?>%]
                            [<span class="percentToStopLoss"><?= $collection->percentToStopLoss() ?>%</span>]
                        </div>
                    </div>
                </div>

                <div class="col-sm-2 col-768-3 col-680-0">
                    <div class="description-block">
                        <span class="description-percentage text-<?= $collection->typeClass() ?>">
                            <i class="fa fa-caret-up"></i>
                            <span class="stockDate">
                                <?= $collection->getDateDiffDays() ?> дней
                            </span>
                        </span>
                        <h5 class="description-header">
                            <?= $formatter->asDate($collection->getDate()) ?>
                        </h5>
                    </div>
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="row">
                <div class="col-lg-3 col-xs-12">
                    <div class="small-box bg-aqua">
                        <div class="inner">
                            <h3><?= $formatter->asCurrency($collection->totalPrice(), $collection->getCurrency()) ?></h3>
                            <p>Начальная стоимость</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-card"></i>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-xs-12">
                    <div class="small-box bg-aqua">
                        <div class="inner">
                            <h3><?= $formatter->asCurrency($collection->getCurrentPriceFull(), $collection->getCurrency()) ?></h3>
                            <p>Текущая стоимость + дивиденды</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-card"></i>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-xs-12">
                    <div class="small-box bg-aqua">
                        <div class="inner">
                            <h3><?= $formatter->asCurrency($collection->getProfitTotal(), $collection->getCurrency()) ?></h3>
                            <p>Прибыль/убыток + дивиденды</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-card"></i>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-xs-12">
                    <div class="small-box bg-<?= $collection->typePercentTotal() ?>">
                        <div class="inner">
                            <h3><?= $collection->getPercentTotal() ?> %</h3>
                            <p>Изменение с дивидендами %</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-card"></i>
                        </div>
                    </div>
                </div>
            </div>

            <table class="table table-condensed table-portfolio-stock">
                <tbody>
                <tr>
                    <th>Цена пок.</th>
                    <th>Кол-во</th>
                    <th>Стоим.пок.</th>
                    <th>Стоим.тек.</th>
                    <th>Дивы</th>
                    <th>Прибыль</th>
                    <th>Изм, %</th>
                    <th>Изм++, %</th>
                    <th>Дата</th>
                    <th></th>
                </tr>
                <?php foreach ($collection->collections as $portfolioStock): ?>
                    <tr>
                        <td>
                            <?= $formatter->stockCurrency($portfolioStock->getPrice(), $collection->getCurrency()) ?>
                        </td>
                        <td>
                            <?= $portfolioStock->quantity ?>
                        </td>
                        <td>
                            <?= $formatter->asCurrency($portfolioStock->totalPrice(), $collection->getCurrency()) ?>
                        </td>
                        <td>
                            <?= $formatter->asCurrency($portfolioStock->totalPriceCurrent(), $collection->getCurrency()) ?>
                        </td>
                        <td>
                            <?= $formatter->asCurrency($portfolioStock->dividend(), $collection->getCurrency()) ?>
                        </td>
                        <td>
                            <?= $formatter->asCurrency($portfolioStock->profit(), $collection->getCurrency()) ?>
                        </td>
                        <td>
                            <?= $portfolioStock->percent() ?>%
                        </td>
                        <td>
                            <?= $portfolioStock->percentTotal() ?>%
                        </td>
                        <td>
                            <?= $formatter->asDate($portfolioStock->date) ?>
                        </td>
                        <td class="action">
                            <?= Html::a('<i class="fa fa-eye"></i>',
                                ['portfolio/stock-view', 'stock_id' => $portfolioStock->id]
                            ) ?>
                            <?= ModalWidget::widget([
                                'url' => ['portfolio/stock-update', 'stock_id' => $portfolioStock->id],
                                'content' => '<i class="fa fa-edit"></i>',
                            ]) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <div style="text-align: center">
                <?= ModalWidget::widget([
                    'url' => ['/portfolio/stock-close', 'id' => $model->id, 'stock_id' => $portfolioStock->stock_id],
                    'content' => 'Продать акции',
                    'cssClass' => 'btn btn-primary',
                ]) ?>
            </div>
        </div>
    </div>
<?php endforeach; ?>

backend/views/portfolio/_view-pjax.php
<?php

/* @var $this yii\web\View */
/* @var $model common\models\Portfolio */
/* @var $stockGroup common\models\portfolio\PortfolioStockCollection[] */

use common\helpers\AdminLteHelper;

$formatter = Yii::$app->formatter;
?>

<?= $this->render('_view-cart', ['model' => $model]) ?>

<div style="text-align:center; padding-bottom:10px">
    <strong>Сортировать по:</strong>
    <span data-sort=".stockName">
        названию
        <span class="arrow"></span>
    </span>
    &#8661;
    <span data-sort=".percentDay" data-sort-value="float">
        изм. день
        <span class="arrow"></span>
    </span>
    &#8661;
    <span data-sort=".currentPercent" data-sort-value="float">
        изменению
        <span class="arrow"></span>
    </span>
    &#8661;
    <span data-sort=".currentPrice" data-sort-value="float">
        цене
        <span class="arrow"></span>
    </span>
    &#8661;
    <span data-sort=".stockProportion" data-sort-type="desc" data-sort-value="float">
        доля
        <span class="arrow"></span>
    </span>
    &#8661;
    <span data-sort=".percentToPurpose" data-sort-type="desc" data-sort-value="float">
        тейк
        <span class="arrow"></span>
    </span>
    &#8661;
    <span data-sort=".percentToStopLoss" data-sort-type="desc" data-sort-value="float">
        стоп
        <span class="arrow"></span>
    </span>
    &#8661;
    <span data-sort=".stockDate" data-sort-value="int">
        дата
        <span class="arrow">&#9660;</span>
    </span>
</div>

<?= $this->render('_view-collection', ['model' => $model, 'stockGroup' => $stockGroup]) ?>

backend/views/portfolio/view.php
<?php

use common\models\stock\StockEntity;
use common\widgets\Modal\ModalWidget;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Portfolio */
/* @var $searchModel common\models\PortfolioStockSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $stockGroup common\models\portfolio\PortfolioStockCollection[] */
/* @var $stockGroupClose common\models\portfolio\PortfolioStockCollection[] */

$formatter = Yii::$app->formatter;

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Портфели', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="portfolio" role="document">
    <div id="portfolio-view-pjax">
        <?= $this->render('_view-pjax', ['model' => $model, 'stockGroup' => $stockGroup]) ?>
    </div>

    <div style="text-align:center;padding:10px 0 15px">
        <?= ModalWidget::widget([
            'url' => ['/portfolio/stock-create', 'id' => $model->id],
            'content' => 'Добавить акцию',
            'cssClass' => 'btn btn-danger',
        ]) ?>
        <?php if ($model->stock_type !== StockEntity::TYPE_BOND) : ?>
            <?= Html::a('Облигации',
                ['/portfolio/view', 'id' => $model->id, 'type' => StockEntity::TYPE_BOND],
                ['class' => 'btn btn-success']
            ) ?>
        <?php endif; ?>
        <?php if ($model->stock_type !== StockEntity::TYPE_STOCK) : ?>
            <?= Html::a('Акции',
                ['/portfolio/view', 'id' => $model->id, 'type' => StockEntity::TYPE_STOCK],
                ['class' => 'btn btn-primary']
            ) ?>
        <?php endif; ?>
        <?php if ($model->stock_type) : ?>
            <?= Html::a('Все',
                ['/portfolio/view', 'id' => $model->id],
                ['class' => 'btn btn-success']
            ) ?>
        <?php endif; ?>
        <?= Html::a('Закрытые позиции', ['/portfolio/view-close', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
    </div>
</div>

<div class="charts">
    <?= $this->render('_charts', ['model' => $model]) ?>
</div>

<script>
    var data = {id: <?= $model->id ?>};

    <?php if ($model->stock_type): ?>
        data = {id: <?= $model->id ?>, type: <?= $model->stock_type ?>};
    <?php endif; ?>

    var interval = setInterval(function () {
        $.get('/portfolio/view-update', data, function (data) {
            for (var meta in data.meta) {
                $('.' + meta).html(data.meta[meta]);
            }

            for (var key in data.items) {
                var block = $('.ticker-' + key);

                for (var keyClass in data.items[key]) {
                    var element = block.find('.' + keyClass);

                    if (element.hasClass('bg-i')) {
                        var newVal = parseFloat(data.items[key][keyClass].replace(' ', '').replace(',', '.'));
                        var currentVal = element.text().replace(/^\s+/, '').replace(' ', '').replace(',', '.');
                        currentVal = parseFloat(currentVal);

                        if (currentVal > newVal) {
                            element.addClass('bg-red').addClass('interval').removeClass('bg-green');
                        }

                        if (currentVal < newVal) {
                            element.addClass('bg-green').addClass('interval').removeClass('bg-red');
                        }
                    }

                    element.html(data.items[key][keyClass]);
                }
            }
        });
    }, 3000);

    setInterval(function () {
        $('.interval.disabled')
            .removeClass('interval')
            .removeClass('disabled')
            .removeClass('bg-red')
            .removeClass('bg-green');

        $('.interval').addClass('disabled');
    }, 1000);

    setTimeout(function () {
        $('[data-sort]').click(function () {
            var _this = $(this);
            var sorted = $('.box-collection');
            var sortClass = _this.data('sort');
            var sortType = _this.data('sort-type');
            var sortValue = _this.data('sort-value');

            $('[data-sort]').find('.arrow').text('');

            sorted.sort(function (a, b) {
                var val1 = $(a).find(sortClass).text()
                    .replace(/^\s+/, '').replace(' ', '').replace(',', '.');
                var val2 = $(b).find(sortClass).text()
                    .replace(/^\s+/, '').replace(' ', '').replace(',', '.');

                if (sortValue === 'float') {
                    val1 = parseFloat(val1);
                    val2 = parseFloat(val2);
                }

                if (sortValue === 'int') {
                    val1 = parseFloat(val1);
                    val2 = parseFloat(val2);
                }

                if (sortType === 'desc') {
                    _this.data('sort-type', 'asc');
                    _this.find('.arrow').html("&#9660;");

                    return val1 < val2;
                }

                _this.data('sort-type', 'desc');
                _this.find('.arrow').html("&#9650;");

                return val1 > val2;
            }).appendTo(sorted.parent());
        });
    }, 2000);

</script>