backend/controllers/StockController.php
<?php

namespace backend\controllers;

use common\models\stock\StockFuture;
use Yii;
use common\models\stock\StockEntity;
use common\models\stock\StockSearch;
use yii\db\StaleObjectException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * StockController implements the CRUD actions for StockEntity model.
 */
class StockController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all StockEntity models.
     * @return string
     */
    public function actionIndex(): string
    {
        $searchModel = new StockSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->setPageSize(100);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionFuture(): string
    {
        $searchModel = new StockSearch();

        $searchModel->type = StockEntity::TYPE_FUTURE;
        $searchModel->dateStart = date('Y-m-d', time() - 86400 * 3);

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->setPageSize(100);

        return $this->render('future', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param int|null $id
     *
     * @return string|Response
     *
     * @throws yii\db\Exception
     */
    public function actionFutureUpdate(int $id = null): Response|string
    {
        $model = $id ? StockFuture::findOne(['future_id' => $id]) : null;

        if ($model === null) {
            $model = new StockFuture();
            $model->future_id = $id;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['stock/future']);
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderPartial('_future-update', [
                'model' => $model,
            ]);
        }

        return $this->render('_future-update', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single StockEntity model.
     * @param integer $id
     * @return string
     */
    public function actionView($id): string
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new StockEntity model.
     *
     * @return string|Response
     */
    public function actionCreate(): string|Response
    {
        $model = new StockEntity();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing StockEntity model.
     *
     * @param integer $id
     *
     * @return string|Response
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id): string|Response
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @param $id
     *
     * @return Response
     *
     * @throws NotFoundHttpException
     * @throws StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the StockEntity model based on its primary key value.
     *
     * @param integer $id
     *
     * @return StockEntity the loaded model
     *
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StockEntity::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/stock/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\stock\StockEntity */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="moex-stock-form box box-primary">
    <?php $form = ActiveForm::begin(); ?>
    <div class="box-body table-responsive">
        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'start')->textInput() ?>
    </div>

    <div class="box-footer">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/views/stock/_future-update.php
<?php

use common\widgets\Modal\ModalWidget;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\stock\StockFuture */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="modal-dialog" role="document">
    <div class="box box-primary" role="document">
        <div class="modal-content box-body table-responsive">
            <div class="modal-header">
                <h5 class="modal-title">Сравнение</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <div class="form-new">
                    <?php $form = ActiveForm::begin(); ?>

                        <div class="row" style="margin-top:5px;">
                            <div class="col-md-12">
                                <?= $form->field($model, 'future_id')->textInput() ?>
                            </div>
                            <div class="col-md-12">
                                <?= $form->field($model, 'stock_id')->textInput() ?>
                            </div>
                            <div class="col-md-12">
                                <?= $form->field($model, 'price_future')->textInput() ?>
                            </div>
                            <div class="col-md-12">
                                <?= $form->field($model, 'price_stock')->textInput() ?>
                            </div>
                            <div class="col-md-12">
                                <?= $form->field($model, 'quantity')->textInput() ?>
                            </div>
                            <div class="col-md-12">
                                <?= $form->field($model, 'quantity_position')->textInput() ?>
                            </div>
                        </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>

            <div class="modal-footer">
                <?= ModalWidget::widget([
                    'url' => ['/stock/future-update'],
                    'content' => 'Сохранить',
                    'cssClass' => 'btn btn-success',
                    'sendClass' => 'modal-send-form',
                ]) ?>
                <?= Html::button('Отмена', ['class' => 'btn btn-secondary', 'data-dismiss' => 'modal']) ?>
            </div>
        </div>
    </div>
</div>

backend/views/stock/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\stock\StockEntity */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="moex-stock-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'ticker') ?>

    <?= $form->field($model, 'board') ?>

    <?= $form->field($model, 'name') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/stock/create.php
<?php

/* @var $this yii\web\View */
/* @var $model common\models\StockEntity */

$this->title = 'Create Stock';
$this->params['breadcrumbs'][] = ['label' => 'Moex Securities', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="moex-stock-create">

    <?= $this->render('_form', [
    'model' => $model,
    ]) ?>

</div>

backend/views/stock/future.php
<?php

use common\helpers\MoexHelper;
use common\models\stock\StockEntity;
use common\widgets\Modal\ModalWidget;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel common\models\stock\StockSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Фьючерсы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="moex-stock-index box box-primary">
    <div class="box-body table-responsive no-padding">

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                'id' => [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'id',
                    'headerOptions' => ['style' => 'width:80px;'],
                ],
                'name' => [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'name',
                    'value' => function (StockEntity $model) {
                        return mb_substr($model->name, 0, 24);
                    },
                ],
                'ticker' => [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'ticker',
                    'headerOptions' => ['style' => 'width:120px;'],
                    'contentOptions' => function (StockEntity $model) {
                        return ['title' => $model->name];
                    },
                ],
                'stock' => [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'stock',
                    'value' => function (StockEntity $model) {
                        return $model->futureStock->stock->ticker ?? '-';
                    },
                ],
                'date_prev' => [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'date_prev',
                    'format' => 'date',
                    'headerOptions' => ['style' => 'width:140px;'],
                    'contentOptions' => function () {
                        return ['style' => 'text-align:center;'];
                    },
                ],
                'price_prev' => [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'price_prev',
                    'format' => 'currency',
                    'contentOptions' => function () {
                        return ['style' => 'text-align:right;'];
                    },
                ],
                'price_stock' => [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'price_stock',
                    'label' => 'Цена актива',
                    'contentOptions' => function () {
                        return ['style' => 'text-align:right;'];
                    },
                    'value' => function (StockEntity $model) {
                        $price = $model->futureStock->stock->price_prev ?? null;

                        if ($price === null) {
                            return '-';
                        }

                        return Yii::$app->formatter->asCurrency($price);
                    },
                ],
                'percent_diff' => [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'percent_diff',
                    'label' => 'Разница',
                    'contentOptions' => function () {
                        return ['style' => 'text-align:right;'];
                    },
                    'value' => function (StockEntity $model) {
                        $percent = $model->futureStock->percent_diff ?? null;

                        if ($percent === null) {
                            return '-';
                        }

                        return Yii::$app->formatter->asPercent($percent / 100, 2);
                    },
                ],
                'position' => [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'position',
                    'label' => 'Позиция % ₽',
                    'format' => 'raw',
                    'contentOptions' => function () {
                        return ['style' => 'text-align:center;white-space:nowrap'];
                    },
                    'value' => function (StockEntity $model) {
                        $futureStock = $model->futureStock;

                        if ($futureStock === null || $futureStock->price_future === null || $futureStock->price_stock === null ) {
                            return '-';
                        }

                        $priceStock = $futureStock->stock->price_prev ?? null;

                        if ($model->price_prev === null || $priceStock === null) {
                            return '-';
                        }

                        $priceStock = $priceStock * $futureStock->quantity;
                        $priceStockFuture = $futureStock->price_stock * $futureStock->quantity;

                        if ($futureStock->price_future > $priceStockFuture) {
                            $priceDiff = $futureStock->price_future - $model->price_prev;
                            $priceDiff += $priceStock - $priceStockFuture;

                            $percent = ($model->price_prev / $futureStock->price_future - 1) * -1;
                            $percent += $priceStock / $priceStockFuture - 1;
                        } else {
                            $priceDiff = $model->price_prev - $futureStock->price_future;
                            $priceDiff += $priceStockFuture - $priceStock;

                            $percent = $model->price_prev / $futureStock->price_future - 1;
                            $percent += $priceStockFuture / $priceStock  - 1;
                        }

                        $priceDiff = $priceDiff * ($futureStock->quantity_position ?: 1);

                        $value = Yii::$app->formatter->asPercent($percent, 2);
                        $value .= ' ' . Yii::$app->formatter->asCurrency($priceDiff);

                        return Html::tag('span', $value);
                    },
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{view} {future-update}',
                    'buttons' => [
                        'future-update' => function ($url) {
                            return ModalWidget::widget([
                                'url' => $url,
                                'content' => '<i class="fa fa-edit"></i>',
                            ]);
                        },
                    ],
                ],
            ],
        ]); ?>
    </div>
</div>

backend/views/stock/index.php
<?php

use common\helpers\MoexHelper;
use common\models\stock\StockEntity;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel common\models\stock\StockSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Акции';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="moex-stock-index box box-primary">
    <div class="box-body table-responsive no-padding">

        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                'id',
                'ticker' => [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'ticker',
                    'contentOptions' => function (StockEntity $model) {
                        return ['title' => $model->name];
                    },
                ],
                'class_code',
                'name',
                'date_prev',
                'price_prev',
                'price_ytd_max',
                'price_ytd_min',
                'percent_ytd_max' => [
                    'attribute' => 'percent_ytd_max',
                    'contentOptions' => function ($model) {
                        return ['class' => 'text-right ' . MoexHelper::maxColor($model)];
                    },
                ],
                'percent_ytd_min',
                'percent_day',
                'percent_ytd',
                'percent_year',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{view}',
                ],
            ],
        ]); ?>
    </div>
</div>

backend/views/stock/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\StockEntity */

$this->title = 'Update Moex Stock: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Moex Securities', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="moex-stock-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/stock/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\stock\StockEntity */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Moex Securities', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="moex-stock-view box box-primary">
    <div class="box-header">
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary btn-flat']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger btn-flat',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </div>
    <div class="box-body table-responsive no-padding">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'ticker',
                'board',
                'name',
                'price_prev',
                'lot_size',
                'face_value',
                'status',
                'decimals',
                'remarks',
                'market_code',
                'instr',
                'sector',
                'min_step',
                'face_unit',
                'currency',
                'date_prev',
                'issue_size',
                'isin',
                'type',
            ],
        ]) ?>
    </div>
</div>