common/models/CalendarEvent.php
<?php

namespace common\models;

use common\components\ActiveModel;
use common\helpers\CalendarHelper;
use common\helpers\DateHelper;
use common\helpers\SettingsHelper;
use common\traits\SignsTrait;
use yii\db\ActiveQuery;
use yii\helpers\Html;

/**
 * This is the model class for table "calendar_event".
 *
 * @property int $id
 * @property string $date Дата
 * @property string|null $time Время
 * @property int $parent_id Основное событие
 * @property int $calendar_id Календарь
 * @property int|null $status_id Статус
 * @property string $name Название
 * @property int $value Значение
 * @property string|null $image Картинка
 * @property string|null $style_class Класс стилей
 * @property string|null $description_short Описание краткое
 * @property string|null $description Описание
 * @property int|null $signs Признаки
 * @property int|null $user_id Пользователь
 * @property string|null $created_at
 * @property string|null $updated_at
 *
 * @property CalendarSubscribe[] $subscribes
 * @property Calendar $calendar
 */
class CalendarEvent extends ActiveModel
{
    use SignsTrait;

    /** @var int */
    public $repeat;

    public $type;

    public $interval;

    public $dateTo;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'calendar_event';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date', 'calendar_id', 'name'], 'required'],
            [['date', 'time', 'created_at', 'updated_at'], 'safe'],
            [['calendar_id', 'status_id', 'signs'], 'default', 'value' => null],
            [['value'], 'safe'],
            [['dateTo', 'interval'], 'safe'],
            [['calendar_id', 'user_id', 'parent_id', 'status_id', 'signs', 'value', 'type', 'repeat'], 'integer'],
            [['description'], 'string'],
            [['name', 'image', 'style_class', 'description_short'], 'string', 'max' => 255],
            [['calendar_id'], 'exist', 'skipOnError' => true, 'targetClass' => Calendar::class, 'targetAttribute' => ['calendar_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Дата',
            'time' => 'Время',
            'calendar_id' => 'Календарь',
            'parent_id' => 'Основное событие',
            'status_id' => 'Статус',
            'name' => 'Название',
            'value' => 'Значение',
            'image' => 'Картинка',
            'style_class' => 'Стиль',
            'description_short' => 'Краткое описание',
            'description' => 'Описание',
            'user_id' => 'Пользователь',
            'signs' => 'Signs',
            'interval' => 'Повторять',
            'dateTo' => 'до даты',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'repeat' => 'Количество копий',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCalendar(): ActiveQuery
    {
        return $this->hasOne(Calendar::class, ['id' => 'calendar_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubscribes(): ActiveQuery
    {
        return $this->hasMany(CalendarSubscribe::class, ['event_id' => 'id']);
    }

    public function getTime(): string
    {
        if ($this->time) {
            return substr($this->time, 0, 5);
        }

        return 'В/Д';
    }

    public function monthName(): string
    {
        [$year, $month,] = explode('-', $this->date);
        return DateHelper::monthName($month) . ' ' . $year;
    }

    public function dateTime(): string
    {
        $date = $this->date;

        if ($this->time) {
            $date .= ' ' . $this->time;
        } else {
            $date .= ' 00:00:00';
        }

        return $date;
    }

    public function isTimer(): bool
    {
        if ($this->time) {
            $date = new \DateTime();
            $date->add(new \DateInterval('P1D'));

            if ($this->date === date('Y-m-d') && $this->time > date('H:i:s')) {
                return true;
            }
            if ($this->date === $date->format('Y-m-d') && $this->time < date('H:i:s')) {
                return true;
            }
        }

        return false;
    }

    public function isTimerDay(): ?string
    {
        if ($this->time) {
            if ($this->isTimer()) {
                return '%H:%M:%S';
            }

            $date = new \DateTime();
            $date->add(new \DateInterval('P1D'));

            $diff = $date->diff(new \DateTime($this->date));

            if ($diff->days > 9) {
                return null;
            }

            if ($this->date > $date->format('Y-m-d')) {
                return '%Dд %Hч';
            }

            if ($this->date === $date->format('Y-m-d') && $this->time > date('H:i:s')) {
                return '%Dд %Hч';
            }
        }

        return null;
    }

    public function countdownFormat()
    {
        $format = '%Hч %Mм %Sс';

        $date = new \DateTime($this->dateTime());
        $date->add(new \DateInterval('P1D'));

        $diff = $date->diff(new \DateTime(), true);
        if ($diff->days > 1) {
            $format = '%Dд ' . $format;
        }

        return $format;
    }

    public function getStyleClass(): string
    {
        if (!$this->style_class) {
            return CalendarHelper::TYPE_DANGER;
        }

        return $this->style_class;
    }

    public function createChild(): void
    {
        if ($this->id && $this->dateTo && $this->interval) {
            $date = new \DateTime($this->date);
            $date->add(new \DateInterval($this->interval));

            while ($date->format('Y-m-d') <= $this->dateTo) {
                $child = self::findOne([
                    'parent_id' => $this->id,
                    'date' => $date->format('Y-m-d')
                ]);

                if (!$child) {
                    $child = new CalendarEvent();
                    $child->parent_id = $this->id;
                    $child->date = $date->format('Y-m-d');
                }

                $child->name = $this->name;
                $child->calendar_id = $this->calendar_id;
                $child->style_class = $this->style_class;
                $child->value = $this->value;

                $child->save();

                $date->add(new \DateInterval($this->interval));
            }
        }
    }

    public function nameHtml(bool $isTime = false): string
    {
        $class = 'text';

        if ($this->style_class) {
            $class .= ' text-' . $this->style_class;
        }

        if (CalendarHelper::getStatusAlias($this->status_id)) {
            $class .= ' text-' . CalendarHelper::getStatusAlias($this->status_id);
        }

        $name = $this->name;
        if ($isTime && $this->time !== null) {
            $name = $this->getTime() . ' ' . $this->name;
        }

        return Html::tag('span', $name, [
            'class' => $class,
        ]);
    }

    public function htmlDescription(): string
    {
        if ($this->value) {
            return 'Значение: <b>' . $this->value . '</b>';
        }

        return $this->description ?: 'нет описания';
    }

    public function isSubscribe()
    {
        if (SettingsHelper::currentUser() === null) {
            return false;
        }

        if (!SettingsHelper::isFirebaseSubscribe()) {
            return false;
        }

        if ($this->dateTime() <= date('Y-m-d H:i:s')) {
            return false;
        }

        return true;
    }

    public function iconSubscribe()
    {
        foreach ($this->subscribes as $subscribe) {
            if ($subscribe->user_id = SettingsHelper::currentUserId()) {
                return '<i class="fas fa-deaf text-secondary pull-right"></i>';
            }
        }

        return '<i class="fas fa-bullhorn text-success pull-right"></i>';
    }
}

backend/controllers/CalendarEventController.php
<?php

namespace backend\controllers;

use common\components\AccessControlCalendar;
use common\models\Calendar;
use common\models\CalendarSubscribe;
use common\models\CalendarUser;
use common\models\User;
use Yii;
use common\models\CalendarEvent;
use common\models\search\CalendarEventSearch;
use common\components\BaseCalendarController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * CalendarEventController
 */
class CalendarEventController extends BaseCalendarController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControlCalendar::class,
                'calendar' => $this->calendar,
                'calendarEvent' => $this->calendarEvent,
                'rules' => [
                    [
                        'actions' => ['view', 'subscribe'],
                        'allow' => true,
                        'roles' => [CalendarUser::SING_VIEW],
                    ],
                    [
                        'actions' => ['update', 'copy',  'clear', 'create', 'delete'],
                        'allow' => true,
                        'roles' => [CalendarUser::SING_UPDATE],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * {@inheritDoc}
     */
    public function beforeAction($action)
    {
        if(Yii::$app->request->get('id')){
            $this->calendarEvent = $this->findEventModel(Yii::$app->request->get('id'));
            $this->calendar = $this->calendarEvent->calendar;
        }

        return parent::beforeAction($action);
    }

    /**
     * Lists all CalendarEvent models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CalendarEventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CalendarEvent model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionCreate()
    {
        $model = new CalendarEvent();

        $model->calendar_id = Yii::$app->request->get('calendar_id');
        $model->date = Yii::$app->request->get('date');
        $model->user_id = Yii::$app->user->getId();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->dateTo && $model->interval) {
                $model->createChild();
            }

            if ($model->repeat) {
                for ($i = 1; $i < $model->repeat; ++$i) {
                    $child = new CalendarEvent();
                    $child->setAttributes($model->attributes);
                    $child->save();
                }
            }

            $calendar = $this->findCalendarModel($model->calendar_id);
            $calendar->updated_at = date('Y-m-d H:i:s');
            $calendar->save();

            if (Yii::$app->request->isAjax) {
                $calendar = new CalendarController($this->id, $this->module);
                return $calendar->actionEvent($model->calendar_id, $model->date);
            }

            return $this->redirect(['/calendar/view', 'id' => $model->calendar_id]);
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing CalendarEvent model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->dateTo && $model->interval) {
                $model->createChild();
            }

            if (Yii::$app->request->isAjax) {
                $calendar = new CalendarController($this->id, $this->module);
                return $calendar->actionEvent($model->calendar_id, $model->date);
            }

            return $this->redirect(['/calendar/view', 'id' => $model->calendar_id]);
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param integer $calendar_id
     * @param string $date
     * @param string $dateTo
     */
    public function actionCopy(int $calendar_id, string $date, string $dateTo = null)
    {
        $model = new CalendarEvent();
        $model->calendar_id = $calendar_id;
        $model->date = $date;
        $model->dateTo = $dateTo;

        $model->load(Yii::$app->request->post());

        if ($model->dateTo) {
            $events = CalendarEvent::findAll([
                'calendar_id' => $model->calendar_id,
                'date' => $model->date,
            ]);

            foreach ($events as $event) {
                $clone = ((int) $model->type === 1) ? $event : new CalendarEvent();
                $clone->load($event->attributes, '');
                $clone->date = $model->dateTo;
                $clone->save();
            }

            $calendar = $this->findCalendarModel($calendar_id);
            $calendar->updated_at = date('Y-m-d H:i:s');
            $calendar->save();

            if (Yii::$app->request->isAjax) {
                $calendar = new CalendarController($this->id, $this->module);
                return $calendar->actionEvent($calendar_id, $model->dateTo);
            }
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('copy', ['model' => $model]);
        }

        return $this->render('copy', ['model' => $model]);
    }

    /**
     * @param integer $calendar_id
     * @param string $date
     */
    public function actionClear($calendar_id, $date)
    {
        CalendarEvent::deleteAll([
            'calendar_id' => $calendar_id,
            'date' => $date,
        ]);

        if (Yii::$app->request->isAjax) {
            $calendar = new CalendarController($this->id, $this->module);
            return $calendar->actionEvent($calendar_id, $date);
        }

        return $this->redirect(['/calendar/view', 'id' => $calendar_id]);
    }

    /**
     * @param integer $id
     * @param string $token
     */
    public function actionSubscribe($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $event = $this->findEventModel($id);

        $content = '<i class="fas fa-bullhorn text-success pull-right"></i>';

        $subscribe = CalendarSubscribe::findOne([
            'event_id' => $id,
            'user_id' => Yii::$app->getUser()->getId(),
        ]);

        if ($subscribe === null) {
            $subscribe = new CalendarSubscribe();

            $subscribe->event_id = $event->id;
            $subscribe->user_id = Yii::$app->getUser()->getId();
            $subscribe->calendar_id = $event->calendar_id;
            $subscribe->date = $this->calendarEvent->dateTime();

            $subscribe->save();

            $content = '<i class="fas fa-deaf text-secondary pull-right"></i>';
        } else {
            $subscribe->delete();
        }

        return ['reloadBlock' => [['selector' => '[data-id=' . $id . ']', 'content' => $content]]];
    }

    /**
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        if ($model->calendar->canUser(CalendarUser::SING_UPDATE)) {
            CalendarEvent::deleteAll(['parent_id' => $model->id]);
            $model->delete();
        }

        if (Yii::$app->request->isAjax) {
            $calendar = new CalendarController($this->id, $this->module);
            return $calendar->actionEvent($model->calendar_id, $model->date);
        }

        return $this->redirect(['/calendar/view', 'id' => $model->calendar_id]);
    }

    /**
     * @param integer $id
     * @return CalendarEvent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CalendarEvent::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/calendar-event/_form.php
<?php

use common\helpers\CalendarHelper;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model common\models\CalendarEvent */
/* @var $form yii\widgets\ActiveForm */
/* @var $formId yii\widgets\ActiveForm */
?>

<div class="calendar-event-form">

    <?php $form = ActiveForm::begin(['id' => $formId]); ?>

    <div class="row">
        <div class="col-md-7">
            <?= $form->field($model, 'name')->textInput() ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'time') ->dropDownList(CalendarHelper::timeList()) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'value')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'style_class')->dropDownList(CalendarHelper::$styleClassList) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'status_id')->dropDownList(CalendarHelper::$statusList) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'repeat')->dropDownList(CalendarHelper::repeatSelect()) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'date')->widget(
                DatePicker::class, [
                'options' => ['placeholder' => 'Выберите дату...'],
                'value' => $model->date,
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pluginOptions' => [
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]);?>
        </div>

        <div class="col-md-4">
            <?= $form->field($model, 'interval')->dropDownList([
                '' => 'Не повторять',
                'P1D' => 'Каждый день',
                'P2D' => 'Через день',
                'P3D' => 'Через два день',
                'P4D' => 'Через три день',
                'P7D' => 'Каждую неделю',
                'P1М' => 'Каждую месяц',
            ]) ?>
        </div>

        <div class="col-md-4">
            <?= $form->field($model, 'dateTo')->widget(
                DatePicker::class, [
                'options' => ['placeholder' => 'Выберите дату по...'],
                'value' => $model->date,
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pluginOptions' => [
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]);?>
        </div>
    </div>

    <?= $form->field($model, 'description')->textarea(['rows' => 1]) ?>

    <?php ActiveForm::end(); ?>

</div>

backend/views/calendar-event/_item-countdown.php
<?php
/* @var $this yii\web\View */

use common\widgets\Countdown;
use common\widgets\Modal\ModalWidget;
use yii\helpers\Html;

/* @var $model common\models\CalendarEvent */

$countdownId = 'countdown-event-' . $model->id;
$eventDelete = "function(){ $('#" . $countdownId . "').text('прошло'); }";
?>

<div class="col-md-6 item-countdown">
    <div class="card mb-4">
        <div class="row no-gutters">
            <div class="col-md-12">
                <div class="card-body center">
                    <h5 class="card-title">
                        <?= ModalWidget::widget([
                            'url' => [
                                '/calendar/event',
                                'calendar_id' => $model->calendar_id,
                                'date' => $model->date,
                            ],
                            'content' => $model->name,
                        ]) ?>
                        <?= Html::a(
                            '<i class="fas fa-calendar-alt"></i>',
                            ['/calendar/view', 'id' => $model->calendar_id]
                        ) ?>
                    </h5>
                    <p class="card-text card-text-24">
                        <?= Countdown::widget([
                            'id' => $countdownId,
                            'datetime' => $model->dateTime(),
                            'format' => $model->countdownFormat(),
                            'tagName' => 'span',
                            'events' => ['finish' => $eventDelete],
                        ]) ?>
                    </p>
                    <p class="card-text">
                        <small class="text-muted">
                            Дата: <?= Yii::$app->formatter->asDate($model->date) . ' ' . $model->getTime() ?>
                        </small>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/calendar-event/_item.php
<?php
/* @var $this yii\web\View */

use common\models\CalendarUser;
use common\widgets\Countdown;
use common\widgets\Modal\ModalWidget;

/* @var $model common\models\CalendarEvent */

$format = $model->isTimerDay();
?>

<li class="item">
    <div class="product-time">
        <div><?= $model->getTime() ?></div>
        <?php if ($format): ?>
            <div class="timer">
                <?= Countdown::widget([
                    'id' => 'countdown-' . $model->id,
                    'datetime' => $model->date . ' ' . $model->getTime(),
                    'format' => $format,
                    'tagName' => 'span',
                ])?>
            </div>
        <?php endif; ?>
    </div>
    <div class="product-info">
        <span href="" class="product-title">
            <?= $model->nameHtml() ?>

            <?php if ($model->calendar->canUserSing(CalendarUser::SING_UPDATE)): ?>
                <?= ModalWidget::widget([
                    'content' => '<i class="fas fa-times pull-right"></i>',
                    'url' => ['/calendar-event/delete', 'id' => $model->id],
                    'cssClass' => 'text-danger',
                    'options' => ['data-request-method' => 'POST'],
                ]) ?>
                <?= ModalWidget::widget([
                    'content' => '<i class="fas fa-edit pull-right"></i>',
                    'url' => ['/calendar-event/update', 'id' => $model->id],
                ]) ?>
                <?php if ($model->isSubscribe()): ?>
                    <?= ModalWidget::widget([
                        'content' => $model->iconSubscribe(),
                        'url' => ['/calendar-event/subscribe', 'id' => $model->id],
                        'cssClass' => 'text-success subscribe-event',
                        'options' => ['data' => ['type' => 'json', 'id' => $model->id]],
                    ]) ?>
                <?php endif; ?>
            <?php endif; ?>
        </span>
        <span class="product-description">
              <?= $model->htmlDescription() ?>
        </span>
    </div>
</li>

backend/views/calendar-event/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\CalendarEventSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="calendar-event-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'time') ?>

    <?= $form->field($model, 'calendar_id') ?>

    <?= $form->field($model, 'status_id') ?>

    <?php // echo $form->field($model, 'name') ?>

    <?php // echo $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'style_class') ?>

    <?php // echo $form->field($model, 'description_short') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'signs') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/calendar-event/copy.php
<?php

use common\models\Calendar;
use common\widgets\Modal\ModalWidget;
use kartik\date\DatePicker;
use yii\bootstrap\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model \common\models\CalendarEvent */

$this->title = $model->name;

if ($model->calendar instanceof Calendar) {
    $this->params['breadcrumbs'][] = [
        'label' => $model->calendar->name,
        'url' => ['/calendar/view', 'id' => $model->calendar_id]
    ];
}

if (!$model->dateTo) {
    $model->dateTo = date('Y-m-d', time() + 60*60*24);
}

$this->params['breadcrumbs'][] = $this->title;

$formId = 'form-calendar-event';
?>
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Событие</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="calendar-event-form">
                <?php $form = ActiveForm::begin(['id' => $formId]); ?>

                <div class="row">
                    <div class="col-md-6">
                        <?= $form->field($model, 'type') ->dropDownList([2 => 'Копия', 1 => 'Перенос']) ?>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 'dateTo')->widget(DatePicker::class, [
                            'options' => ['placeholder' => 'Выберите дату...'],
                            'value' => $model->date,
                            'type' => DatePicker::TYPE_COMPONENT_APPEND,
                            'pluginOptions' => [
                                'autoclose' => true,
                                'format' => 'yyyy-mm-dd'
                            ]
                        ]);?>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
        <div class="modal-footer">
            <?= ModalWidget::widget([
                'url' => ['/calendar-event/copy', 'calendar_id' => $model->calendar_id, 'date' => $model->date],
                'content' => 'Сохранить',
                'cssClass' => 'btn btn-success',
                'options' => ['data' => ['request-form' => $formId]],
            ]) ?>
            <?= Html::button('Отмена', ['class' => 'btn btn-secondary', 'data-dismiss' => 'modal']) ?>
        </div>
    </div>
</div>

backend/views/calendar-event/create.php
<?php

use common\models\Calendar;
use common\widgets\Modal\ModalWidget;
use yii\bootstrap\Html;

/* @var $this yii\web\View */
/* @var $model \common\models\CalendarEvent */

$this->title = $model->name;

if ($model->calendar instanceof Calendar) {
    $this->params['breadcrumbs'][] = [
        'label' => $model->calendar->name,
        'url' => ['/calendar/view', 'id' => $model->calendar_id]
    ];
}

$this->params['breadcrumbs'][] = $this->title;

$formId = 'form-calendar-event';
?>
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Событие</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <?=$this->render('_form', ['model' => $model, 'formId' => $formId])?>
        </div>
        <div class="modal-footer">
            <?= ModalWidget::widget([
                'url' => ['/calendar-event/create'] + Yii::$app->request->get(),
                'content' => 'Сохранить',
                'cssClass' => 'btn btn-success',
                'options' => ['data' => ['request-form' => $formId]],
            ]) ?>
            <?= Html::button('Отмена', ['class' => 'btn btn-secondary', 'data-dismiss' => 'modal']) ?>
        </div>
    </div>
</div>

backend/views/calendar-event/update.php
<?php

use common\models\Calendar;
use common\widgets\Modal\ModalWidget;
use yii\bootstrap\Html;

/* @var $this yii\web\View */
/* @var $model \common\models\CalendarEvent */

$this->title = $model->name;

if ($model->calendar instanceof Calendar) {
    $this->params['breadcrumbs'][] = [
        'label' => $model->calendar->name,
        'url' => ['/calendar/view', 'id' => $model->calendar_id]
    ];
}

$this->params['breadcrumbs'][] = $this->title;

$formId = 'form-calendar-event';
?>
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Событие</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <?=$this->render('_form', ['model' => $model, 'formId' => $formId])?>
        </div>
        <div class="modal-footer">
            <?= ModalWidget::widget([
                'url' => ['/calendar-event/update', 'id' => $model->id],
                'content' => 'Сохранить',
                'cssClass' => 'btn btn-success',
                'options' => ['data' => ['request-form' => $formId]],
            ]) ?>
            <?= Html::button('Отмена', ['class' => 'btn btn-secondary', 'data-dismiss' => 'modal']) ?>
        </div>
    </div>
</div>