common/models/Calendar.php
<?php

namespace common\models;

use common\components\ActiveModel;
use common\helpers\SettingsHelper;
use common\models\interfaces\SignsInterface;
use common\traits\SignsTrait;
use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "calendar".
 *
 * @property int $id
 * @property string $name Название
 * @property string $alias Алиас
 * @property string|null $image Картинка
 * @property string|null $description_short Описание краткое
 * @property string|null $keywords Ключевые слова
 * @property string|null $description Описание
 * @property int|null $signs Признаки
 * @property int $user_id Пользователь
 * @property string $params Параметры
 * @property string|null $date_start Дата начала
 * @property string|null $created_at
 * @property string|null $updated_at
 *
 * @property-read User $user
 * @property-read CalendarUser[] $calendarUsers
 * @property-read null|CalendarUser $calendarUser
 * @property-read CalendarEvent[] $calendarEvents
 */
class Calendar extends ActiveModel implements SignsInterface
{
    use SignsTrait;

    public const SIGN_IS_PUBLIC = 0;

    public const SIGN_VIEW_META = 1;

    public const SIGN_VIEW_DIFF = 2;

    public const SIGN_VIEW_LINK = 3;

    public const SIGN_SELECT_YEAR = 4;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'calendar';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'user_id'], 'required'],
            [['description'], 'string'],
            [['signs', 'user_id'], 'default', 'value' => null],
            [['signs', 'user_id'], 'integer'],
            [['params', 'inputSigns', 'date_start', 'created_at', 'updated_at'], 'safe'],
            [['name', 'alias', 'image', 'description_short', 'keywords'], 'string', 'max' => 255],
            [['alias'], 'unique'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'alias' => 'Alias',
            'image' => 'Image',
            'description_short' => 'Описание краткое',
            'keywords' => 'Ключевые слова',
            'description' => 'Описание',
            'signs' => 'Signs',
            'user_id' => 'User ID',
            'params' => 'Параметры',
            'params[dangerName]' => 'Параметр[danger]',
            'date_start' => 'Дата начала',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->inputSigns) {
            $this->setSigns($this->inputSigns);
        }

        if (!$this->alias) {
            $this->alias = md5(time());
        }

        return parent::beforeSave($insert);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    /**
     * @return CalendarUser
     */
    public function getCalendarUser(): ?CalendarUser
    {
        foreach ($this->calendarUsers as $user) {
            if ($user->user_id == SettingsHelper::currentUserId()) {
                return $user;
            }
        }

        return null;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCalendarUsers(): \yii\db\ActiveQuery
    {
        return $this->hasMany(CalendarUser::class, ['calendar_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCalendarEvents()
    {
        return $this->hasMany(CalendarEvent::class, ['calendar_id' => 'id']);
    }

    public static function signsLabels(): array
    {
        return [
            self::SIGN_IS_PUBLIC => 'Публичный календарь',
            self::SIGN_VIEW_META => 'Показывать сумму',
            self::SIGN_VIEW_DIFF => 'Показывать разницу дней',
            self::SIGN_VIEW_LINK => 'Доступен по ссылке',
            self::SIGN_SELECT_YEAR => 'Выбор года',
        ];
    }

    public function getParamValue(string $name, string $default = null): string
    {
        if ($this->params) {
            if (isset($this->params[$name])) {
                return $this->params[$name];
            }
        }

        if ($default) {
            return $default;
        }

        return $name;
    }

    public function getStatusName(string $name, string $default = null): string
    {
        if ($this->params && isset($this->params['n'])) {
            if (isset($this->params['n'][$name]) && $this->params['n'][$name]) {
                return $this->params['n'][$name];
            }
        }

        if ($default) {
            return $default;
        }

        return $name;
    }

    /**
     * Проверка доступности
     *
     * @param int|null $userId
     *
     * @return bool
     */
    public function canUser(int $userId = null): bool
    {
        if ($this->canSign(self::SIGN_IS_PUBLIC)) {
            return true;
        }

        if ($this->user_id === $userId) {
            return true;
        }

        if ($this->calendarUser instanceof CalendarUser) {
            return true;
        }

        return false;
    }

    /**
     * Проверка доступности действия
     *
     * @param int|null $userId
     *
     * @return bool
     */
    public function canUserSing(int $sing, int $userId = null): bool
    {
        if ($this->canSign(Calendar::SIGN_IS_PUBLIC)) {
            if ($sing === CalendarUser::SING_VIEW) {
                return true;
            }
        }

        if ($this->canSign(Calendar::SIGN_VIEW_LINK)) {
            if ($sing === CalendarUser::SING_VIEW_LINK) {
                return true;
            }
        }

        if ($userId === null) {
            $userId = SettingsHelper::currentUserId();

            if ($userId === null) {
                return false;
            }
        }

        if ($this->user_id === $userId) {
            return true;
        }

        if ($this->calendarUser instanceof CalendarUser) {
            if ($this->calendarUser->canSign($sing)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Проверка доступности на обновление
     *
     * @param int|null $userId
     *
     * @return bool
     */
    public function canUpdate(int $userId = null): bool
    {
        if ($this->user_id === $userId) {
            return true;
        }

        if (!$this->calendarUser instanceof CalendarUser) {
            $query = CalendarUser::find();
            $query->where(['user_id' => $userId, 'calendar_id' => $this->id]);
            $this->calendarUser = $query->one();
        }

        if ($this->calendarUser instanceof CalendarUser) {
            return $this->calendarUser->canSign(CalendarUser::SING_UPDATE);
        }

        return false;
    }

    public function getLink()
    {
        return Url::to(['/calendar/alias/' . $this->alias], true);
    }
}

backend/controllers/CalendarController.php
<?php

namespace backend\controllers;

use common\components\AccessControlCalendar;
use common\helpers\SettingsHelper;
use common\models\CalendarUser;
use common\models\search\CalendarEventSearch;
use common\models\Calendar;
use common\models\search\CalendarSearch;
use common\components\BaseCalendarController;
use Yii;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * CalendarController implements the CRUD actions for Calendar model.
 */
class CalendarController extends BaseCalendarController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControlCalendar::class,
                'calendar' => $this->calendar,
                'rules' => [
                    [
                        'actions' => ['view', 'event', 'month'],
                        'allow' => true,
                        'roles' => [CalendarUser::SING_VIEW],
                    ],
                    [
                        'actions' => ['update', 'join', 'user'],
                        'allow' => true,
                        'roles' => [CalendarUser::SING_UPDATE],
                    ],
                    [
                        'actions' => ['create', 'alias'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @param $action
     *
     * @return bool
     *
     * @throws NotFoundHttpException
     */
    public function beforeAction($action): bool
    {
        if(Yii::$app->request->get('id')){
            $this->calendar = $this->findModel(Yii::$app->request->get('id'));
        }

        if(Yii::$app->request->get('alias')){
            $this->calendar = $this->findByAlias(Yii::$app->request->get('alias'));
        }

        return parent::beforeAction($action);
    }

    /**
     * Lists all Calendar models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CalendarSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = $this->findCalendarModel($id);

        $searchModel = new CalendarEventSearch();
        $searchModel->load(Yii::$app->request->get());
        $searchModel->calendar_id = $model->id;

        return $this->render('view', [
            'model' => $model,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUser($id)
    {
        $model = $this->findCalendarModel($id);

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('user', ['model' => $model]);
        }

        return $this->render('user', [
            'model' => $model,
        ]);
    }

    /**
     * @param integer $id
     * @param integer $model_id
     *
     * @return mixed
     *
     * @throws NotFoundHttpException
     */
    public function actionJoin($id, $model_id = null)
    {
        $calendar = $this->findCalendarModel($id);

        if ($model_id) {
            $model = CalendarUser::findOne($model_id);
        }

        if (!isset($model) || !$model instanceof CalendarUser) {
            $model = new CalendarUser();
        }

        $model->calendar_id = $calendar->id;

        if (Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            $model->save();

            if (Yii::$app->request->isAjax) {
                return $this->renderAjax('user', ['model' => $calendar]);
            }
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('join', ['model' => $model]);
        }

        return $this->render('join', [
            'model' => $model,
        ]);
    }

    /**
     * @param integer $calendar_id
     * @param string $date
     *
     * @return mixed
     */
    public function actionEvent($calendar_id, $date)
    {
        $model = $this->findModel($calendar_id);

        $searchModel = new CalendarEventSearch();
        $searchModel->calendar_id = $model->id;

        $date = new \DateTime($date);

        $searchModel->date = $date->format('Y-m-d');
        $searchModel->startYear = $date->format('Y');
        $searchModel->startMonth = $date->format('m');

        $dataProvider = $searchModel->search([]);
        $dataProvider->pagination = false;

        if (Yii::$app->request->isAjax) {
            if (Yii::$app->request->get('type') === 'month') {
                Yii::$app->response->format = Response::FORMAT_JSON;

                $content = $this->renderPartial('view-month', [
                    'model' => $model,
                    'searchModel' => $searchModel,
                ]);

                return ['reloadBlock' => [
                    [
                        'selector' => '.month-' . $date->format('n'),
                        'content' => $content,
                    ],
                ]];
            }

            return $this->renderAjax('/calendar-event/index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }

        return $this->render('/calendar-event/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Calendar();
        $model->user_id = Yii::$app->getUser()->getId();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            \Yii::$app->session->remove(SettingsHelper::KEY_EXISTS_CALENDAR);

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findCalendarModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            \Yii::$app->session->remove(SettingsHelper::KEY_EXISTS_CALENDAR);

            return $this->redirect(['view', 'id' => $model->id]);
        }

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param integer $id
     * @return mixed
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel(int $id): Calendar
    {
        return $this->findCalendarModel($id);
    }

    protected function findByAlias(string $alias): Calendar
    {
        if ($this->calendar instanceof Calendar) {
            if ($this->calendar->alias === $alias) {
                return $this->calendar;
            }
        }

        $this->calendar = Calendar::findOne(['alias' => $alias]);

        if ($this->calendar !== null) {
            return $this->calendar;
        }

        throw new NotFoundHttpException('Календарь не найден');
    }
}

backend/views/calendar/_form.php
<?php

use common\helpers\CalendarHelper;
use common\helpers\SettingsHelper;
use common\helpers\SignsHelper;
use common\models\Calendar;
use vova07\imperavi\Widget;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model common\models\Calendar */
/* @var $form yii\widgets\ActiveForm */
/* @var $formId string */

if (!isset($formId)) {
    $formId = 'form-calendar';
}
?>

<div class="calendar-form">

    <?php $form = ActiveForm::begin(['id' => $formId]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description_short')->textInput(['maxlength' => true]) ?>

    <div>
        <?= $form->field($model, 'date_start')->widget(
            DatePicker::class, [
            'options' => ['placeholder' => 'Выберите дату...'],
            'value' => $model->date_start,
            'type' => DatePicker::TYPE_INPUT,
            'pluginOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd',
                'orientation' => 'top right',
            ]
        ]); ?>
    </div>

    <?= $form->field($model, 'keywords')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->widget(Widget::class, [
        'settings' => [
            'lang' => 'ru',
            'allowedTags' => SettingsHelper::$allowedTags,
            'replaceDivs' => false,
            'minHeight' => 200,
            'plugins' => [
                'clips',
                'fullscreen',
                'table',
            ],
            'clips' => [
                ['Lorem ipsum...', 'Lorem...'],
                ['red', '<span class="label-red">red</span>'],
                ['green', '<span class="label-green">green</span>'],
                ['blue', '<span class="label-blue">blue</span>'],
            ],
        ],
    ]) ?>

    <div class="collapse-title">
        <div class="collapsed" data-toggle="collapse" data-target="#collapseParam" aria-expanded="false" aria-controls="collapseParam">
            Параметры
            <span  class="collapse-icon">
                <i class="fas fa-angle-up"></i>
            </span>
        </div>
    </div>
    <div class="collapse" id="collapseParam">
        <div class="row">
            <?php foreach (CalendarHelper::getStyleList() as $key => $name): ?>
                <?php if ($key === '') continue; ?>
                <?php $attribute = 'params[n][' . $key . ']'; ?>
                <?php $label = 'Название "' . $name . '"'; ?>
                <div class="col-md-3">
                    <?= $form->field($model, $attribute)->textInput()->label($label) ?>
                </div>
            <?php endforeach; ?>
            <div class="col-md-3">
                <?= $form->field($model, 'params[totalCountName]')->textInput()->label('Общее') ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'params[totalSumName]')->textInput()->label('Сумма') ?>
            </div>
        </div>
    </div>

    <div class="row" style="padding-top:15px">
        <?php foreach (Calendar::signsLabels() as $key => $label): ?>
            <div class="col-md-3">
                <?= SignsHelper::checkbox($form, $model, $key) ?>
            </div>
        <?php endforeach; ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/calendar/_item.php
<?php

use common\models\CalendarUser;
use common\widgets\Modal\ModalWidget;
use yii\bootstrap\Html;

/* @var $model \common\models\Calendar */
?>

<li class="item">
    <div class="product-img">
        <img src="/images/default-50x50.gif" alt="Product Image">
    </div>
    <div class="product-info">
    <span href="" class="product-title">
        <?= Html::a($model->name, ['/calendar/view', 'id' => $model->id]) ?>
        <?php if ($model->canUserSing(CalendarUser::SING_UPDATE)): ?>
            <?= ModalWidget::widget([
                'content' => '<i class="fas fa-edit pull-right"></i>',
                'url' => ['/calendar/update', 'id' => $model->id],
                'cssClass' => 'right',
                'modal' => 'calendar-create',
            ]) ?>
        <?php endif; ?>
    </span>
    <span class="product-description">
        <?= $model->description_short ?: 'нет описания' ?>
    </span>
    </div>
</li>

backend/views/calendar/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\CalendarSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="calendar-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'alias') ?>

    <?= $form->field($model, 'image') ?>

    <?= $form->field($model, 'description_short') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'signs') ?>

    <?php // echo $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/calendar/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Calendar */

$this->title = 'Добавить календарь';
$this->params['breadcrumbs'][] = ['label' => 'Календари', 'url' => ['/calendar']];
$this->params['breadcrumbs'][] = $this->title;

$formId = 'form-calendar';
?>

<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                <?= $this->title ?>
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <?= $this->render('_form', ['model' => $model, 'formId' => $formId]) ?>
        </div>
        <div class="modal-footer">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success', 'form' => $formId]) ?>
            <button type="button" class="btn btn-secondary" data-dismiss="modal" style="z-index:9999">
                Закрыть
            </button>
        </div>
    </div>
</div>

backend/views/calendar/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Calendar */

$this->title = 'Календарь: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Календари', 'url' => ['/calendar']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = $this->title;

$formId = 'form-calendar';
?>

<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                <?= $this->title ?>
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <?= $this->render('_form', ['model' => $model, 'formId' => $formId]) ?>
        </div>
        <div class="modal-footer">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success', 'form' => $formId]) ?>
            <button type="button" class="btn btn-secondary" data-dismiss="modal" style="z-index:9999">
                Закрыть
            </button>
        </div>
    </div>
</div>

backend/views/calendar/user.php
<?php

use common\widgets\Modal\ModalWidget;

/* @var $model \common\models\Calendar */

$this->title = 'События календаря';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                Пользователи <?= $model->name ?>
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="box box-primary">
                <div class="box-body">
                    <ul class="products-list product-list-in-box" style="margin-top:20px">
                        <?php foreach ($model->calendarUsers as $user): ?>
                            <li class="item">
                                <div class="product-time">
                                    <div>12 34</div>
                                </div>
                                <div class="product-info">
                                    <span class="product-title">
                                        <?= $user->user->firstname . ' ' . $user->user->lastname ?>

                                        <?= ModalWidget::widget([
                                            'content' => '<i class="fas fa-times pull-right"></i>',
                                            'url' => ['/calendar/delete', 'id' => $model->id],
                                            'cssClass' => 'text-danger',
                                            'options' => ['data-request-method' => 'POST'],
                                        ]) ?>
                                        <?= ModalWidget::widget([
                                            'content' => '<i class="fas fa-edit pull-right"></i>',
                                            'url' => ['/calendar/join', 'id' => $model->id, 'model_id' => $user->id],
                                        ]) ?>
                                    </span>
                                    <span class="product-description">
                                          <?= 'тут будут роли' ?>
                                    </span>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="modal-footer" style="text-align:center">
            <button type="button" class="btn btn-secondary" data-dismiss="modal" style="float:left">
                <i class="fas fa-times"></i>
            </button>

            <?= ModalWidget::widget([
                'url' => ['/calendar/join', 'id' => $model->id],
                'content' => '<i class="fas fa-plus"></i>',
                'cssClass' => 'btn btn-primary',
            ]) ?>
        </div>
    </div>
</div>

backend/views/calendar/view-month.php
<?php

use common\widgets\Calendar;

/* @var $this yii\web\View */
/* @var $model common\models\Calendar */
/* @var $searchModel common\models\search\CalendarEventSearch */

$search = clone $searchModel;
$search->date = null;
?>

<?= Calendar::widget([
    'dateStart' => $searchModel->dateStart(),
    'searchModel' => $search,
    'popoverTitle' => false,
    'url' => ['/calendar/event', 'calendar_id' => $model->id],
    'urlIsAjax' => true,
    'urlIsEmpty' => true,
    'isMetaData' => true,
    'isMonthOne' => true,
    'popoverDiff' => $model->canSign($model::SIGN_VIEW_DIFF),
]) ?>

backend/views/calendar/view.php
<?php

use common\helpers\DateHelper;
use common\helpers\SettingsHelper;
use common\models\CalendarUser;
use common\widgets\Calendar;
use common\widgets\Modal\ModalWidget;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\web\YiiAsset;

/* @var $this yii\web\View */
/* @var $model common\models\Calendar */
/* @var $searchModel common\models\search\CalendarEventSearch */

$this->title = $model->name;

if ($searchModel->startYear) {
    $this->title .= ' ' . $searchModel->startYear . ' год';
}

$this->params['breadcrumbs'][] = ['label' => 'Календари', 'url' => ['/calendar']];
$this->params['breadcrumbs'][] = $this->title;

YiiAsset::register($this);

$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->keywords ?: SettingsHelper::getKeywords(),
], 'keywords');
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->description_short ?: SettingsHelper::getDescription(),
], 'description');

if ($searchModel->startYear === null) {
    $searchModel->startYear = (new DateTime($model->date_start ?: 'now'))->format('Y');
}

//$this->registerJs("$('.modal-remote-view').last().click();");
?>
<div class="calendar-view">
    <?php if ($model->canSign(\common\models\Calendar::SIGN_SELECT_YEAR)): ?>
        <div>
            <?php $form = ActiveForm::begin([
                'action' => ['view', 'id' => $model->id],
                'method' => 'get',
            ]); ?>

            <div class="row" style="text-align:center">
                <div class="col-md-3"></div>

                <div class="col-md-2">
                    <?= $form->field($searchModel, 'startYear')
                        ->dropDownList(DateHelper::yearsList())
                        ->label(false)
                    ?>
                </div>

                <div class="col-md-2">
                    <?= $form->field($searchModel, 'startMonth')
                        ->dropDownList(DateHelper::$monthName)
                        ->label(false)
                    ?>
                </div>

                <div class="col-md-1" style="text-align:left">
                    <?= Html::submitButton('Показать', ['class' => 'btn btn-primary']) ?>
                </div>

                <div class="col-md-2"></div>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    <?php endif; ?>

    <div class="row list-calendar">
        <?= Calendar::widget([
            'dateStart' => $searchModel->dateStart(new DateTime($model->date_start)),
            'searchModel' => $searchModel,
            'popover' => SettingsHelper::isNotMobile(),
            'popoverTitle' => false,
            'url' => ['/calendar/event', 'calendar_id' => $model->id],
            'urlIsAjax' => true,
            'urlIsEmpty' => $model->canUserSing(CalendarUser::SING_UPDATE),
            'isMetaData' => true,
            'popoverDiff' => $model->canSign($model::SIGN_VIEW_DIFF),
        ]) ?>
    </div>

    <?php if ($model->canUserSing(CalendarUser::SING_UPDATE)): ?>
        <div class="row" style="padding-bottom:15px">
            <div class="col-md-12" style="text-align: center">
                <?= ModalWidget::widget([
                    'url' => ['user', 'id' => $model->id],
                    'content' => 'Пользователи',
                    'cssClass' => 'btn btn-success',
                ]) ?>
                <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </div>
        </div>

        <?php if ($model->canSign(\common\models\Calendar::SIGN_VIEW_LINK)): ?>
            <div class="calendar-link" style="text-align:center;padding-top:10px">
                Поделится: <?= Html::input('input', 'link', $model->getLink()) ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <div class="calendar-description">
        <?= $model->description ?>
    </div>
</div>

<div style="display:none">
    <?= ModalWidget::widget([
        'url' => ['event', 'calendar_id' => $model->id, 'date' => $model->date_start],
        'content' => 'Пользователи',
        'cssClass' => 'btn btn-success',
        'options' => ['data-hide' => 'true'],
    ]) ?>
</div>

<?php if (Yii::$app->request->get('date')): ?>
    <script>
        setTimeout(function () {
            $('[data-date=<?= Yii::$app->request->get('date') ?>]').click();
        }, 500);
    </script>
<?php endif; ?>